//! `user-actor-supervisor` — launches the user actor into the interactive
//! session.
//!
//! Trigger: the marker process from config (`platform.non_s0_process`,
//! legacy `explorer`) starting under ETW — the same signal the target
//! launcher uses. One attempt per boot; the per-boot nonce is passed on the
//! command line and must be echoed in the IPC `HELLO` (anti-impostor).
//!
//! The `user_actor.started` wire event is NOT emitted here — it is evidence-
//! based: the IPC server publishes it when a `HELLO` actually verifies.

use std::sync::{
    Arc,
    atomic::{
        AtomicBool,
        AtomicU32,
        Ordering,
    },
};

use async_trait::async_trait;
use kernel::app::plugin_ports::{
    middleware_plugin_port::{
        MiddlewarePluginPort,
        Next,
    },
    plugin_port::PluginPort,
};
use protocol::config::AgentConfig;

use crate::{
    app::{
        builder::AgentServices,
        event::SandboxEvent,
    },
    domain::marker::is_marker_process,
    ports::process_launcher::{
        LaunchSpec,
        ProcessLauncherPort,
    },
};

/// Argument that carries the per-boot nonce to the user actor.
pub const NONCE_ARGUMENT: &str = "--nonce";

/// Constructor dependencies.
pub struct UserActorSupervisorDeps {
    /// Full agent config (`user_actor.path`, `platform.non_s0_process`).
    pub config: Arc<AgentConfig>,
    /// Interactive-session launcher (mechanism per `platform.launch_mechanism`).
    pub launcher: Arc<dyn ProcessLauncherPort>,
    /// Per-boot shared secret, generated by the composition root and shared
    /// with the IPC server.
    pub nonce: String,
    /// Expected-client-pid gate shared with the IPC server: after a
    /// successful launch with a known pid, the gate is set and the server
    /// rejects `HELLO`s from any other client process.
    pub pid_gate: Arc<AtomicU32>,
}

/// User-actor supervisor plugin (pipeline middleware).
pub struct UserActorSupervisorPlugin {
    deps: UserActorSupervisorDeps,
    /// One launch attempt per boot.
    attempted: AtomicBool,
}

impl UserActorSupervisorPlugin {
    /// Assemble the plugin.
    #[must_use]
    pub fn new(deps: UserActorSupervisorDeps) -> Self {
        Self { deps, attempted: AtomicBool::new(false) }
    }

    /// Build the launch spec: the configured user-actor binary with the nonce
    /// argument. No working directory — the binary is expected next to the
    /// agent or at an absolute path from config.
    #[must_use]
    pub fn launch_spec(&self) -> LaunchSpec {
        LaunchSpec {
            path: self.deps.config.user_actor.path.clone(),
            args: vec![NONCE_ARGUMENT.to_owned(), self.deps.nonce.clone()],
            working_dir: None,
        }
    }
}

#[async_trait]
impl PluginPort for UserActorSupervisorPlugin {
    fn name(&self) -> &'static str {
        "user-actor-supervisor"
    }
}

#[async_trait]
impl MiddlewarePluginPort<SandboxEvent, AgentServices> for UserActorSupervisorPlugin {
    async fn pre(&self, event: &mut SandboxEvent, _services: &AgentServices) -> Next {
        if let SandboxEvent::Source(crate::app::event::SourceEvent::ProcessStarted(data)) = event {
            if is_marker_process(&self.deps.config.platform.non_s0_process, &data.name)
                && !self.attempted.swap(true, Ordering::SeqCst)
            {
                let spec = self.launch_spec();
                match self.deps.launcher.launch(&spec).await {
                    Ok(outcome) => {
                        if let Some(pid) = outcome.pid {
                            // Arm the IPC server's anti-impostor check; 0 is
                            // the "ungated" sentinel, real pids are never 0.
                            self.deps.pid_gate.store(pid.max(1), Ordering::SeqCst);
                        }
                        tracing::info!(path = %spec.path, pid = ?outcome.pid, "user actor launched");
                    }
                    Err(error) => {
                        // A failed launch must not crash the session (the
                        // screenshots/reactive features degrade gracefully).
                        tracing::error!(path = %spec.path, %error, "user actor launch failed");
                    }
                }
            }
        }
        Next::Continue
    }
}
